unique_ids:
  forms:
    Balance_Slide: 52CJWUGWW5MTHOZJ5HGSWG4EAJSSBWZB
    Home: TCYQ7IZVWAJIEW7B7SWBFN3PPRF5RPVJ
    Input_Load: VTMEJ5RXNPWTDZKK5TTPJVUDB34MLB5D
    Load_Confirm: Y2KNYGSTUYFVVYTXMDHX7C4KWBX5RF6H
    Login: OGQOWUKKCL3N5PNGV7UKYLBCOMIFHHFN
    Unload_Page: VH2LLLGK2AIFYCONNLI6F5JCBMDL4PKT
  modules: {}
  server_modules:
    Balance: UUPLNDBKUNBUTGGGAQ75LUZ5MS5OBMWO
    DataManagement: QRTGNJZQY4HS75SEBXIIY5IK5SKQ4Y74
    LU: LPEBFAWKGMPTGJRGKSBVYZFNF5TSTVNW
    Scratch: CBIZVWU6SZ6SHGKW2YMDVZKPMFPSPLZB
  assets:
    standard-page.html: NCJO4B66YQMOHXKJTUG7QN4UMH7ETFXP
    theme.css: 6XQ2JNDOGLPNUKVZQSFSYLTGGBS4NCAE
